from .department import Department
from .course import Course
from .student import Student
from .admin import Admin
from .result import Result
from .test import Test
from .activity_log import ActivityLog
from .semester import Semester
from .session import Session
